project:
  type: website

website:
  title: "My Quarto Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - blog/

format:
  html:
    theme: cosmo
    css: styles.css
