project:
  type: website

website:
  title: "My Quarto Site"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - post1.qmd
        text: Blog
  page-footer: "© 2025 Your Name"
format:
  html:
    theme: cosmo
    css: styles.css
